name: express_all
description: A new Flutter project.

# Prevent accidental publishing to pub.dev.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.19.4 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_onboarding_slider: ^1.0.11
  google_fonts: ^4.0.4
  flutter_svg: ^2.0.9
  get: ^4.6.6
  logger: ^2.0.2+1
  reorderables: ^0.6.0
  firebase_core: ^2.24.2
  firebase_database: ^10.4.0
  firebase_auth: ^4.16.0
  fluttertoast: 8.2.2
  cloud_firestore: ^4.14.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
    - assets/images/svg/
    - assets/images/emotion_gesture_recognition/
    - assets/images/emotion_gesture_recognition/face_expressions/
    - assets/images/emotion_gesture_recognition/gesture_recognition/
    - assets/images/task_management/
    - assets/images/task_management/task_identification/
    - assets/images/task_management/task_sequencing/
    - assets/images/task_management/priority_setting/
    - assets/images/score_page/
