name: express_all
description: A new Flutter project.

# Prevent accidental publishing to pub.dev.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.19.4 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_onboarding_slider: ^1.0.11
  google_fonts: ^4.0.4
  flutter_svg: ^2.0.9
  get: ^4.6.6
  logger: ^2.0.2+1
  reorderables: ^0.6.0
  google_vision: ^1.1.1+2
  camera: ^0.10.5+9
  http: ^1.2.0
  meta: ^1.7.0
  syncfusion_flutter_charts: ^24.1.47+2
  image_picker: ^1.0.7
  firebase_core: ^2.24.2
  firebase_database: ^10.4.0
  firebase_auth: ^4.16.0
  fluttertoast: 8.2.2
  cloud_firestore: ^4.14.0
  flutter_launcher_icons: ^0.13.1
  vertical_percent_indicator: ^0.0.1
  chat_bubbles: ^1.5.0
  url_launcher: ^6.2.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/expressall_icon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/images/expressall_icon.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "assets/images/expressall_icon.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/images/expressall_icon.png"

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
    - assets/images/svg/
    - assets/images/emotion_gesture_recognition/
    - assets/images/emotion_gesture_recognition/face_expressions/
    - assets/images/emotion_gesture_recognition/gesture_recognition/
    - assets/images/task_management/
    - assets/images/task_management/task_identification/
    - assets/images/task_management/task_sequencing/
    - assets/images/task_management/priority_setting/
    - assets/images/score_page/
